const PATHS = {
    welcome1: require('../../../src/assets/images/welcome/welcome1.png'),
    welcome2: require('../../../src/assets/images/welcome/welcome2.png'),
    welcome3: require('../../../src/assets/images/welcome/welcome3.png'),
    signIn: require('../../../src/assets/images/signin.png'),
    signUp: require('../../../src/assets/images/signup.png'),
    winners: require('../../../src/assets/images/winners.png'),
    cup: require('../../../src/assets/images/cup.png'),
    phone: require('../../../src/assets/images/phone.png'),
    bike: require('../../../src/assets/images/bike.png'),
    promotion: require('../../../src/assets/images/promotion.png'),
    cashPoints: require('../../../src/assets/images/cashPoints.png'),
    logo: require('../../../src/assets/images/logo.png'),
    foodcup: require('../../../src/assets/images/foodcup.png'),
    food: require('../../../src/assets/images/food.png'),
    forget: require('../../../src/assets/images/forget.png'),
    celebration: require('../../../src/assets/images/celebration.png'),
    ordering: require('../../../src/assets/images/settings/ordering.jpg'),
    payment: require('../../../src/assets/images/settings/payment.png'),
    delivery: require('../../../src/assets/images/settings/delivery.jpg'),
    feedback: require('../../../src/assets/images/settings/feedback.jpg'),
    promotions: require('../../../src/assets/images/settings/promotions.png'),
    contact: require('../../../src/assets/images/settings/contact.jpg'),
    background: require('../../../src/assets/images/background.png'),
    motivation: require('../../../src/assets/images/motivation.png'),
    green: require('../../../src/assets/images/green.png'),
    tricks: require('../../../src/assets/images/settings/tricks.jpeg'),
    notifications: require('../../../src/assets/images/settings/notifications.jpg'),
    i211: require('../../../src/assets/i211.png'),
    error: require('../../../src/assets/images/error.png'),
}

export default PATHS;
